version: '3.8'

services:
  maft:
    build: .
    container_name: maft-training
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount experiments directory for results
      - ./experiments:/app/experiments
      # Mount logs directory
      - ./logs:/app/logs
      # Mount configs for easy modification
      - ./configs:/app/configs
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
      - WANDB_MODE=disabled  # Disable wandb for containerized training
    command: >
      python scripts/deploy_gcp.py
      --use_mock_data
      --data_dir /app/data/mosei
      --output_dir /app/experiments/mosei_docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  # Service for running only data preparation
  maft-data:
    build: .
    container_name: maft-data-prep
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
    environment:
      - PYTHONPATH=/app
    command: >
      python scripts/prepare_mosei.py
      --output_dir /app/data/mosei
      --use_mock
    profiles:
      - data-only

  # Service for running only evaluation
  maft-eval:
    build: .
    container_name: maft-evaluation
    volumes:
      - ./data:/app/data
      - ./experiments:/app/experiments
      - ./configs:/app/configs
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    command: >
      python evaluate.py
      --config /app/configs/mosei_config.yaml
      --model_path /app/experiments/mosei_docker/best_model.pth
    profiles:
      - eval-only
    depends_on:
      - maft

  # Service for running attention analysis
  maft-attention:
    build: .
    container_name: maft-attention-analysis
    volumes:
      - ./data:/app/data
      - ./experiments:/app/experiments
      - ./configs:/app/configs
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    command: >
      python scripts/analyze_attention.py
      --config /app/configs/mosei_config.yaml
      --model_path /app/experiments/mosei_docker/best_model.pth
    profiles:
      - analysis-only
    depends_on:
      - maft

  # Service for running efficiency analysis
  maft-efficiency:
    build: .
    container_name: maft-efficiency-analysis
    volumes:
      - ./data:/app/data
      - ./experiments:/app/experiments
      - ./configs:/app/configs
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    command: >
      python scripts/efficiency_analysis.py
      --config /app/configs/mosei_config.yaml
    profiles:
      - analysis-only
    depends_on:
      - maft 