# MAFT Configuration for CMU-MOSEI Dataset

dataset:
  name: "mosei"
  data_path: "data/mosei/"
  max_length: 512
  audio_max_length: 1000
  visual_max_length: 1000

model:
  text_model_name: "bert-base-uncased"
  hidden_dim: 768
  num_heads: 12
  num_layers: 1
  audio_input_dim: 74  # COVAREP features
  visual_input_dim: 35  # FACET features
  num_classes: 2
  dropout: 0.1
  modality_dropout_rate: 0.1
  freeze_bert: false

training:
  num_epochs: 20
  batch_size: 2  # Reduced for CPU training
  lr: 0.0001
  bert_lr: 2e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  max_grad_norm: 1.0
  classification_weight: 0.5
  regression_weight: 0.5
  num_workers: 0  # Set to 0 for CPU to prevent hanging
  save_every: 5
  output_dir: "experiments/mosei"

# Ablation study configurations
ablation:
  modalities_to_drop: ["text", "audio", "visual"]
  early_stopping_patience: 5
  num_seeds: 5 